version: 2

defaults:
  - &test_defaults
    docker:
      - image: circleci/python:2.7.14
      - image: rabbitmq:3.7.4
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: cloudify
          POSTGRES_PASSWORD: cloudify
          POSTGRES_DB: cloudify_db

    steps:
      - checkout
      - run: >
          if [ -n "$CI_PULL_REQUEST" ]; then
            PR_ID=${CI_PULL_REQUEST##*/}
            git fetch origin +refs/pull/$PR_ID/merge:
            git checkout -qf FETCH_HEAD
          fi

      - run: |
          sudo pip install -U pip==9.0.1
          sudo pip install tox
          tox -e ${TOX_TEST}

jobs:
  flake8:
    <<: *test_defaults
    environment:
      TOX_TEST: flake8

  py27:
    <<: *test_defaults
    environment:
      TOX_TEST: py27

  build-rpm:
    machine:
      enabled: true

    steps:
      - checkout
      - run: pip install requests
      - run: git clone --depth 1 https://github.com/cloudify-cosmo/cloudify-manager.git ~/cloudify-manager
      - run: |
          cd ~/cloudify-manager
          git fetch --depth 1 origin "${CIRCLE_BRANCH}" && git checkout "${CIRCLE_BRANCH}" || echo no matching branch found, using master
      - run: |
          builder="docker run --cap-add SYS_ADMIN --security-opt apparmor:unconfined \
            --mount type=bind,source=$(pwd),target=/source \
            --mount type=bind,source=${HOME}/cloudify-manager,target=/builder \
            cloudify3/mock-builder:0.1 \
            python /builder/packaging/build_rpm.py"
          $builder /source/packaging/cloudify-amqp-postgres.spec
      - run: mkdir result
      - run: mv ~/cloudify-manager/packaging/*.rpm result

      - store_artifacts:
          path: result
          destination: result


workflows:
  version: 2

  build_and_test:
    jobs:
#      - flake8
      - py27
#      - build-rpm
