version: 2

defaults:
  - &run_test
    run:
      name: Install tox and run test
      command: |
        sudo pip install -U pip==9.0.1
        sudo pip install tox
        tox -e ${TOX_TEST}

jobs:
  flake8:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - *run_test
    environment:
      TOX_TEST: flake8

  py27:
    docker:
      - image: circleci/python:2.7.14
        environment:
          TEST_DATABASE_URL: postgresql://cloudify:cloudify@localhost/cloudify_db
      - image: rabbitmq:3.7.4
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: cloudify
          POSTGRES_PASSWORD: cloudify
          POSTGRES_DB: cloudify_db
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run:
          name: Create executions table
          command: |
            psql -d ${TEST_DATABASE_URL} \
            -c "CREATE TABLE executions (
               id text,
               _storage_id integer,
               _tenant_id integer,
               _creator_id integer
            );"

      - run:
          name: Create events table
          command: |
            psql -d ${TEST_DATABASE_URL} \
            -c "CREATE TABLE events (
                id text,
                \"timestamp\" timestamp NOT NULL,
                message text,
                message_code text,
                event_type text,
                operation text,
                node_id text,
                _execution_fk integer NOT NULL,
                _creator_id integer NOT NULL,
                _tenant_id integer NOT NULL,
                reported_timestamp timestamp NOT NULL,
                error_causes text,
                private_resource boolean,
                visibility text
            );"

      - run:
          name: Create logs table
          command: |
            psql -d ${TEST_DATABASE_URL} \
            -c "CREATE TABLE logs (
                  id text,
                  \"timestamp\" timestamp NOT NULL,
                  message text,
                  message_code text,
                  logger text,
                  level text,
                  operation text,
                  node_id text,
                  _execution_fk integer NOT NULL,
                  _creator_id integer NOT NULL,
                  _tenant_id integer NOT NULL,
                  reported_timestamp timestamp NOT NULL,
                  private_resource boolean,
                  visibility text
              );"
      - *run_test
    environment:
      TOX_TEST: py27

  build-rpm:
    machine:
      enabled: true

    steps:
      - checkout
      - run: pip install requests
      - run: git clone --depth 1 https://github.com/cloudify-cosmo/cloudify-manager.git ~/cloudify-manager
      - run: |
          cd ~/cloudify-manager
          git fetch --depth 1 origin "${CIRCLE_BRANCH}" && git checkout "${CIRCLE_BRANCH}" || echo no matching branch found, using master
      - run: |
          builder="docker run --cap-add SYS_ADMIN --security-opt apparmor:unconfined \
            --mount type=bind,source=$(pwd),target=/source \
            --mount type=bind,source=${HOME}/cloudify-manager,target=/builder \
            cloudify3/mock-builder:0.1 \
            python /builder/packaging/build_rpm.py"
          $builder /source/packaging/cloudify-amqp-postgres.spec
      - run: mkdir result
      - run: mv ~/cloudify-manager/packaging/*.rpm result

      - store_artifacts:
          path: result
          destination: result


workflows:
  version: 2

  build_and_test:
    jobs:
#      - flake8
      - py27
#      - build-rpm
